Revert "dependencies: update rusqlite to 0.26.3 + libsqlite3-sys to 0.23.2"
This reverts commit 9f42d0489e2bcc056f94d0ed74cb6d4568d13f62.

libsqlite3-sys 0.23.2 breaks with MSRV (rustc 1.46.0) with the
following error message:

    error: failed to parse manifest at `/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/libsqlite3-sys-0.23.2/Cargo.toml`

    Caused by:
      feature `resolver` is required

      this Cargo does not support nightly features, but if you
      switch to nightly channel you can add
      `cargo-features = ["resolver"]` to enable this feature